### ISSUE TITLE
Dear sir kindly give example to add module from pypi to this

### ISSUE THREAD

**Issue by petersmith1982a-github1** [mausbrand/pyodide-app-stub#1]
"In case you want to add additional modules, you have to hack the file app.js."

How must I hack app.js to add a module from pypi? Thank you in advance.

**Comment by phorward** [comment]
Hello @petersmith1982a-github1,
for this, you just need Pyodide and not the pyodide-app-stub.
Anyway, I've updated the repository to allow for more pyodide features, like micropip.

Generally it is
```python
import micropip
micropip.install("your-package")
```
you can do it now with the repository here or with the original Pyodide.
